### ISSUE TITLE
Integrate pre-recorded audio file

### ISSUE THREAD

**Issue by mehul4795** [GoogleCloudPlatform/android-docs-samples#9]
Using this project I can convert speech to text but I want to convert already recorded audio file into text file. How can I do that? Please help. Thank You.

**Comment by puneith** [comment]
@yaraki Can you please help answer.

**Comment by yaraki** [comment]
Instead of using VoiceRecorder class, just feed your audio data to the API through ApiFragment#recognize(byte[], int). Note that the audio data needs to be encoded in 16 bit PCM monoral. You also need to specify the sample rate of your recording when you call ApiFragment.startRecognizing(int).

If you always handle static files, you might want to check out REST version of the API as well: https://cloud.google.com/speech/reference/rest/

**Comment by venkataramanaduddu** [comment]
hi @mehul4795,  if u got the code how to do this can u suggest me how to do\is
